# This file was generated by GoReleaser. DO NOT EDIT.
class Lockerdb < Formula
  desc "LockerDB is an in-memory key:value store written in Go."
  homepage "https://github.com/vinothsparrow/lockerdb"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.0.4/lockerdb_0.0.4_macOS_amd64.tar.gz"
    sha256 "86dfb7a2172464b188d2c99930e00d638944276032c0f22491204c8d4d9f17a6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.0.4/lockerdb_0.0.4_linux_amd64.tar.gz"
    sha256 "233ea7151d1a8c73b726e2f1e0d8683816fd20661781412e6c20817c7b823312"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.0.4/lockerdb_0.0.4_linux_armv6.tar.gz"
    sha256 "2bd08150c1e9e74f5e62d1a3acb3cf57e85d5e7a0e593d72f150528e3e3bb22d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.0.4/lockerdb_0.0.4_linux_arm64.tar.gz"
    sha256 "1c2b5625cfe38f54d8dca3efee1d46eb23bdbbd743775358c637cecd9368c650"
  end

  def install
    bin.install "lockerdb-server"
    bin.install "lockerdb-cli"
  end

  test do
    system "#{bin}/lockerdb-cli help"
  end
end
