# This file was generated by GoReleaser. DO NOT EDIT.
class Lockerdb < Formula
  desc "LockerDB is an in-memory key:value store written in Go."
  homepage "https://github.com/vinothsparrow/lockerdb"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.1.0/lockerdb_0.1.0_macOS_amd64.tar.gz"
    sha256 "d40f2d43f60446785ad2c428dc4f94a195ec91d27b2f93602ee4f9d56baf8552"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.1.0/lockerdb_0.1.0_linux_amd64.tar.gz"
    sha256 "0410fea2b796eeeeb3715bb214ded00f291c8d4bcc518ef10d67b0c45385f621"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.1.0/lockerdb_0.1.0_linux_armv6.tar.gz"
    sha256 "395c957aa1c94445e9629a988ef8369d74d73c4ef7509249672870da3e042e9e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vinothsparrow/lockerdb/releases/download/v0.1.0/lockerdb_0.1.0_linux_arm64.tar.gz"
    sha256 "1168abda3681438cb0c8558859ec90e3201d6abc87f55f2d05de99c215ff5275"
  end

  def install
    bin.install "lockerdb-server"
    bin.install "lockerdb-cli"
  end

  test do
    system "#{bin}/lockerdb-cli help"
  end
end
